#page title
page_title                                : Game Knight                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
# ios_app_id                                : 6450722296                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://testflight.apple.com/join/4H3l1ZVE                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Game Knight                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Your perfect game night companion.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Andy Boedo
your_link                                 : https://game-knight.app                     
your_city                                 : Montevideo                                
email_address                             : andresboedo@gmail.com
facebook_username                         :                                           
instagram_username                        : aboedo
twitter_username                          : getgameknight
github_username                           : aboedo
youtube_username                          :
mastodon_link                             : https://toot.io/@andresboedo



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Host Game Nights!
    description                           : Game Knight is the must-have app for every board game enthusiast. Whether you're a casual player or a hardcore gamer, our app enhances your gaming experience and brings more fun to your board game nights.
    fontawesome_icon_name                 : dice
    
  - title                                 : Keep track of matches
    description                           : No more disputes about who won the last game! With Game Knight, you can easily record the results of your games, keep track of player scores, and view detailed game histories.
    fontawesome_icon_name                 : trophy

  - title                                 : Add Players
    description                           : Add your friends, assign them unique avatars, and keep track of everyone's game performance. Who's the reigning champion in your group?
    fontawesome_icon_name                 : users

  - title                                 : Add Games
    description                           : Explore our extensive database of board games. Find detailed information, read reviews, and even discover great deals online. Save your favorites for easy access later.
    fontawesome_icon_name                 : chess-board

  - title                                 : Game Details
    description                           : Find out a lot more about games you like, with easy links to get more information and even deals on games.
    fontawesome_icon_name                 : magic

  - title                                 : Built-in calculator
    description                           : Calculate scores without leaving the app with a built-in calculator.
    fontawesome_icon_name                 : calculator



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.4
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0.7

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000000"

link_color                                : "#693eb6"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#888888"

feature_icons_foreground_color            : "#4a2e80"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#4a2e80"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
